const suggestionDict = {
  a: ["uh", "uhh", "eh", "eah", "aeh"],
  academic: ["academics", "akademik", "academia", "acadamy", "academical"],
  activities: [
    "activity",
    "acclivities",
    "activators",
    "activates",
    "activase"
  ],
  add: ["ad", "abd", "adh", "adde", "addd"],
  after: ["aftr", "after-", "ofter", "iftar", "efter"],
  all: ["aul", "aull", "all-", "aal", "aale"],
  alligators: ["allocators", "alligator", "aligator", "allegator", "allocator"],
  alone: ["alain", "alaine", "a line", "ahlen", "a-line"],
  although: ["all the", "altho", "also", "altha", "aldo"],
  aluminium: ["aluminum", "alumina", "aluminous", "illumina", "illumining"],
  always: ["hallways", "altas", "all white", "all wet", "all eyes"],
  ambiguous: [
    "ambiguity",
    "ambiguously",
    "ambiguousness",
    "ambigu",
    "ambiguities"
  ],
  ambulance: [
    "ambulanse",
    "ambulant",
    "ambivalence",
    "ambulances",
    "imbalance"
  ],
  an: ["ane", "ahn", "-an", "agn", "an-"],
  and: ["und", "unde", "undp", "end", "ende"],
  anecdotal: ["anecdotally", "anecdote", "anecdotes", "antidotal", "anecdotic"],
  annoying: ["enjoying", "canoeing", "inching", "annealing", "alloying"],
  answer: ["anser", "ansar", "ensor", "oncer", "nsr"],
  any: ["eny", "eni", "n.y", "enni", "n e"],
  appeles: ["apiece", "a plus", "appulse", "a piece", "a-plus"],
  appetizers: ["appetisers", "appetizer", "appetiser", "appetize", "apatites"],
  appointed: ["upended", "appended", "unpointed", "appointee", "abounded"],
  appreciated: [
    "appreciative",
    "depreciated",
    "appreciate",
    "abbreviated",
    "appreciates"
  ],
  aptitude: ["aptitud", "attitude", "aptitudes", "altitude", "apatite"],
  are: ["ar", "agr", "ahr", "arh", "a.r"],
  arm: ["arme", "hram", "armm", "armr", "aarn"],
  as: ["azz", "asrt", "ass", "asse", "asce"],
  ask: ["asc", "asq", "asg", "aske", "eisk"],
  at: ["aht", "atc", "adt", "atat", "aqt"],
  atheletic: ["analytic", "athletics", "athematic", "balletic", "catalytic"],
  attitude: ["altitude", "latitude", "aptitude", "attitudes", "lattitude"],
  audition: ["addition", "edition", "aition", "auditioned", "auditioner"],
  audits: ["oddity", "edits", "odets", "addis", "odit"],
  authorization: [
    "authorizations",
    "weatherization",
    "theorization",
    "authorisation",
    "cauterization"
  ],
  bagpipes: ["bagpipe", "bag pipe", "bagpiper", "bagpipers", "back pass"],
  ball: ["bawl", "baul", "baol", "baal", "bahl"],
  based: ["baste", "baist", "bast", "bdst", "baust"],
  bayou: ["biu", "bio", "baya", "baie", "baia"],
  be: ["b.", "bdi", "b.a", "bcl", "bdm"],
  beautiful: [
    "beautifull",
    "beautify",
    "beautifies",
    "beautifier",
    "beautiful boy"
  ],
  bidding: ["bedding", "budding", "beading", "bading", "bedim"],
  bilogists: ["apologists", "ballasts", "pathologists", "belligerents"],
  bongos: ["bongoes", "bongo", "bango", "bingos", "pingos"],
  bought: ["bott", "baht", "bhatt", "baat", "bhot"],
  bowl: ["bole", "boll", "boal", "boel", "bohl"],
  boy: ["boi", "bboy", "boye", "bhoy", "b"],
  cake: ["caique", "cmyk", "cack", "cac", "cacc"],
  can: ["cannes", "cann", "caen", "cahn", "canne"],
  cannot: ["c-note", "canot", "canet", "kanat", "can it"],
  capable: ["keepable", "coupable", "culpable", "skippable", "copiable"],
  carry: ["carey", "cari", "carew", "carie", "carree"],
  case: ["cace", "cayce", "kace", "caisse", "cqc"],
  catastrophic: [
    "catastrophically",
    "katastrophe",
    "catastrofe",
    "catastrophe",
    "catastrophy"
  ],
  cement: ["ciment", "summoned", "summand", "seamount", "samina"],
  chamber: ["chambers", "chambered", "champer", "chamberer", "chambery"],
  citizenship: [
    "citizenships",
    "citizenship day",
    "citizenry",
    "artisanship",
    "citizens"
  ],
  clasp: ["clisp", "clap", "clapp", "casp", "caspe"],
  coconut: ["cocoanut", "coco nut", "kickin it", "coconuts", "carcanet"],
  coincided: ["conceded", "conceited", "coincide", "coincident", "coincides"],
  coleslaw: ["cole slaw", "cold slaw", "cholula", "colella", "whole slew"],
  companions: [
    "companion",
    "companioned",
    "compagnon",
    "companionate",
    "communions"
  ],
  company: ["compagnie", "compony", "companies", "accompany", "compend"],
  contains: ["contends", "contain", "condones", "canteens", "cantons"],
  contributions: [
    "contribution",
    "contributional",
    "distributions",
    "distribution",
    "cerebrations"
  ],
  corner: ["korner", "koerner", "carner", "karner", "carmer"],
  costumes: ["costume", "customs", "costumer", "costumers", "costings"],
  couried: ["corrode", "crad", "cread", "choroid", "corrade"],
  cream: ["creme", "kareem", "karim", "crme", "careme"],
  cubic: ["kubik", "kubic", "cubics", "kubica", "cubica"],
  cut: ["kut", "qut", "kutt", "kutte", "ket"],
  cutbacks: ["cutback", "cut back", "cat box", "comebacks", "cat back"],
  dad: ["dadd", "daad", "aahed", "-ade", "dabt"],
  dark: ["darke", "darc", "dork", "dorch", "dorc"],
  day: ["de", "-ed", "dae", "dei", "daye"],
  deadline: ["dead line", "deadlines", "dateline", "date line", "headline"],
  dessert: ["dessert", "disert", "dissert", "dysart", "deserts"],
  destroy: ["distro", "destro", "destra", "destroyed", "destroyer"],
  did: ["dead", "ded", "dde", "ddc", "ddg"],
  diploma: ["diplomas", "dilemma", "dilema", "diplom", "deplume"],
  disguise: ["disguised", "discos", "disguiser", "descries", "digos"],
  dislikes: ["dislike", "disliked", "delux", "disliker", "deluxe"],
  do: ["dew", "doo", "dmu", "ddu", "ddw"],
  doctor: ["docter", "dr", "dockter", "doktor", "docteur"],
  doctors: ["doctor", "docter", "dockers", "dockter", "docteur"],
  dont: ["donte", "daunt", "dant", "daint", "ddnt"],
  down: ["downe", "doun", "doune", "daan", "dahn"],
  drenched: ["trenched", "drench", "drent", "drenche", "drawn-out"],
  drugs: ["dregs", "driggs", "drags", "droogs", "drogues"],
  drunkard: ["drinkard", "drunker", "drunkards", "dunkard", "trenchard"],
  dwarf: ["dwarfs", "dorf", "dwarfed", "dorff", "dwarfy"],
  each: ["eech", "ege", "eash", "eage", "eaj"],
  early: ["earlie", "earley", "irle", "erla", "irla"],
  easy: ["easie", "easi", "e z", "easa", "e c"],
  economic: [
    "economics",
    "ergonomic",
    "economical",
    "economically",
    "technomic"
  ],
  edge: ["njhs", "gdg", "esch", "eche", "ecce"],
  employee: ["employ", "employed", "employees", "emploi", "empleo"],
  encyclopedias: [
    "encyclopedia",
    "encyclopaedia",
    "encyclopaedias",
    "enciclopedia",
    "encyclopedian"
  ],
  enjoy: ["ngi", "dnf", "enja", "nje", "n g"],
  even: ["evene", "evin", "ovin", "avin", "awen"],
  evening: ["evenings", "even", "inning", "awning", "davening"],
  every: ["evry", "ivre", "avery", "ivery", "avri"],
  everyfile: ["aerofoil", "air rifle", "overfill", "overfull", "overfall"],
  evidence: ["avoidance", "evidenced", "evident", "evidente", "evidences"],
  execute: ["executes", "execrate", "exsiccate", "executed", "executing"],
  eyestrain: ["eye strain", "ice tray", "icetray", "astron", "estrin"],
  fashion: ["fashin", "fission", "foshan", "fushun", "fasching"],
  flimsy: ["flimsies", "flummery", "flames", "flamey", "finzi"],
  for: ["fore", "faur", "faure", "foar", "fore-"],
  freely: ["fraley", "frawley", "frailey", "frailly", "friley"],
  friends: ["fronds", "frenz", "fends", "freds", "fred's"],
  from: ["frum", "frim", "frem", "fram", "frahm"],
  geese: ["gece", "gas", "gass", "gace", "cgs"],
  gives: ["guvs", "govs", "gyves", "give", "giv"],
  glue: ["glew", "glu", "gla", "glaa", "glah"],
  go: ["goe", "gogh", "gau", "goh", "gho"],
  got: ["gott", "gaat", "gout", "gaut", "gowt"],
  government: [
    "goverment",
    "governments",
    "garment",
    "gouvernement",
    "gormand"
  ],
  greasy: ["gracie", "grassy", "gracey", "gracy", "grassi"],
  greatly: ["gradely", "gately", "greyly", "gateley", "grayly"],
  grows: ["grose", "graze", "grays", "graz", "gray's"],
  guess: ["gesse", "ghess", "gus", "guss", "giss"],
  gurantees: ["grantees", "guaranties", "grantee"],
  had: ["hadd", "haad", "habt", "-head", "-hood"],
  hallway: ["whole way", "hallways", "halwa", "haul away", "holloway"],
  hand: ["hande", "hanged", "hamd", "hammed", "hamed"],
  hats: ["hatz", "heights", "hates", "heats", "heitz"],
  hauling: ["halling", "howling", "holling", "hailing", "haling"],
  have: ["halve", "hav", "heave", "heav", "hev"],
  help: ["hellp", "hulp", "halp", "holp", "hilb"],
  her: ["hur", "hurr", "hure", "heur", "lgh"],
  hierarchies: [
    "hierarchy",
    "heirarchy",
    "hierarchie",
    "hierarchs",
    "hierarchic"
  ],
  high: ["hae", "heya", "haj", "hei", "haie"],
  him: ["hymn", "hym", "himn", "himm", "hem"],
  hires: ["highers", "hyers", "high-res", "hairs", "haars"],
  his: ["hiz", "hizz", "has", "hez", "huz"],
  hispanic: ["hispanics", "hispania", "hispano", "hypnic", "messianic"],
  huge: ["hue", "hew", "heu", "hewe", "hewa"],
  hung: ["hing", "heng", "nhj", "hang", "hange"],
  I: ["aye", "ai", "eie", "ajj", "eih"],
  ices: ["isis", "-ise", "isas", "isos", "asses"],
  iguanas: ["iguania", "iguana", "aquinas", "equines", "agana"],
  in: ["inh", "ijn", "-in", "in-", "ihn"],
  into: ["in two", "intu", "indu", "indue", "in tow"],
  intruments: [
    "interments",
    "entrapments",
    "entremets",
    "increments",
    "enticements"
  ],
  is: ["izz", "as", "ehs", "esge", "ehz"],
  isotopes: ["isotope", "stps", "acetose", "icecaps", "ice caps"],
  it: ["itt", "itv", "idt", "itte", "ibd"],
  kayak: ["kyack", "kiack", "n.y.c", "quack", "kwak"],
  lawyer: ["laur", "lawer", "laure", "launer", "laurer"],
  lay: ["lae", "laye", "lait", "laigh", "laie"],
  layoffs: ["layoff", "play offs", "lay off", "play-offs", "lay-off"],
  left: ["lift", "luft", "lyft", "luffed", "laft"],
  lifelong: ["lifeline", "life line", "laflin", "laflamme", "laugh line"],
  light: ["lite", "lighte", "lyte", "leyte", "leit"],
  like: ["leich", "lack", "lac", "lacr", "lacc"],
  loads: ["lodes", "lads", "lades", "lauds", "ladds"],
  made: ["maid", "maide", "maed", "maad", "-mate"],
  makes: ["macs", "macks", "machs", "mac's", "maccs"],
  mango: ["manga", "mingo", "manco", "manko", "mangga"],
  many: ["meni", "mini", "minnie", "minni", "mini-me"],
  me: ["mee", "mea", "meeh", "mhi", "mhr"],
  measured: ["measure", "mared", "majored", "mered", "mithered"],
  medieval: ["medial", "mediaeval", "midvale", "midlevel", "meadville"],
  microoragnisms: [
    "mechanisms",
    "anachronisms",
    "anachronism",
    "americanism",
    "sectarianism"
  ],
  mollusks: ["molluscs", "mollusk", "mollusc", "mollusca", "molex"],
  mom: ["mam", "malm", "mamm", "maam", "ma'am"],
  more: ["moar", "mawr", "mohr", "maure", "maur"],
  morning: ["mourning", "mornings", "moring", "mohring", "moehring"],
  most: ["moste", "massed", "maced", "maist", "-most"],
  museum: ["museums", "musial", "muzio", "musing", "musang"],
  musical: ["musicale", "musicals", "musica", "muzyka", "musial"],
  musicians: ["musician", "mutations", "munitions", "museums", "mutagens"],
  my: ["mai", "mei", "mis-", "maai", "miee"],
  near: ["neer", "nere", "nir", "neir", "niere"],
  neglect: ["neglecter", "neglects", "intellect", "neglected", "analect"],
  new: ["knew", "gnu", "neww", "niue", "neuk"],
  nice: ["gneiss", "nyce", "nyse", "-ness", "gnas"],
  no: ["kno", "knoe", "knowe", "gnow", "gno"],
  noise: ["noyes", "noys", "noix", "gnaws", "knaus"],
  objects: ["object", "abject", "ejects", "objekt", "abjects"],
  of: ["uvs", "ev", "evs", "eof", "evg"],
  off: ["auf", "awf", "ofp", "aaf", "ahf"],
  official: ["oficial", "officially", "officials", "aphasia", "asocial"],
  often: ["offen", "afan", "ifan", "iffen", "ifen"],
  oil: ["eul", "oyl", "eule", "-el", "-ole"],
  oily: ["ailey", "ailee", "-ile", "ahli", "aalii"],
  on: ["mwn", "-on", "nht", "lnn", "nhk"],
  oout: ["o.t", "uut", "otw", "ood", "oohed"],
  oozed: ["eased", "easd", "azd", "ezed", "adzed"],
  opens: ["opines", "oppens", "open", "opan", "opas"],
  out: ["hdtv", "out-", "aot", "aat", "aode"],
  outcast: ["outcaste", "outcasts", "outclassed", "outguessed", "at cost"],
  papaya: ["papaia", "papayas", "papia", "pompeia", "pepa"],
  paper: ["papar", "pauper", "papper", "papr", "papir"],
  participate: [
    "participates",
    "participant",
    "participating",
    "participated",
    "participator"
  ],
  patient: ["patients", "pageant", "passioned", "pallant", "fnt"],
  peck: ["pec", "pek", "pech", "peq", "pecc"],
  people: ["papal", "paypal", "peep hole", "peepul", "papel"],
  pewter: ["puter", "pyotr", "puder", "pudor", "buter"],
  pic: ["pic", "pik", "picke", "picc", "picr"],
  player: ["plier", "plore", "plar", "plor", "plougher"],
  point: ["pointe", "paint", "pant", "pent", "peint"],
  pond: ["pound", "pawned", "lb", "pained", "pand"],
  poor: ["poore", "pair", "paer", "paar", "paire"],
  postponed: [
    "postpone",
    "postpones",
    "postpaid",
    "postponing",
    "poster paint"
  ],
  potatoes: ["potatos", "potato", "potatoe", "patatas", "patooties"],
  prescibe: ["press up", "press-up", "preso", "pressa", "paresseux"],
  present: ["prozent", "prisoned", "peasant", "pesant", "brisant"],
  presented: ["pretended", "prevented", "present", "presenter", "presentee"],
  previous: ["previus", "pervious", "previa", "provis", "previews"],
  problem: ["probleem", "problems", "probably", "preplan", "pablum"],
  prowler: ["proller", "prowl", "brawler", "pearler", "prower"],
  question: ["questions", "questioned", "questioner", "christian", "christion"],
  radioactive: [
    "radio active",
    "retroactive",
    "radiative",
    "radioactively",
    "radio activity"
  ],
  rag: ["ragg", "wrag", "wragg", "areg", "irreg"],
  rain: ["raine", "arraign", "rane", "rayne", "rainn"],
  reading: ["redding", "ridding", "raiding", "reddin", "read in"],
  related: ["relighted", "reloaded", "relented", "relate to", "relucted"],
  remained: ["remand", "raymond", "raymund", "raimond", "raymonde"],
  reorganization: [
    "reorganisation",
    "reorganizations",
    "recognization",
    "reorientation",
    "world organization"
  ],
  reptiles: ["reptile", "reptil", "ripples", "repels", "rattles"],
  results: ["result", "resents", "rosettes", "resits", "arousals"],
  rise: ["arise", "ries", "rize", "ryes", "araise"],
  rob: ["robb", "robbe", "raab", "raabe", "raub"],
  roll: ["rol", "roel", "areole", "roell", "rohl"],
  sat: ["satte", "satt", "ssat", "satd", "ceat"],
  screw: ["scru", "scray", "scre", "scra", "scraw"],
  seldom: ["seldem", "seldon", "selden", "sedam", "celda"],
  serve: ["serv", "surv", "cerv", "saree", "siry"],
  she: ["hse", "hsi", "hcf", "gfci", "hsb"],
  silverware: [
    "silverer",
    "silverwood",
    "self aware",
    "silverish",
    "silver wings"
  ],
  simple: ["simpl", "simpel", "semple", "cymbal", "cimbal"],
  sketched: ["scotched", "sketch", "sketchy", "sket", "scnt"],
  skimask: ["ski mask", "schemas", "ski masks", "schemist", "cimic"],
  small: ["smal", "smel", "smail", "smale", "smeal"],
  social: ["sosial", "sociol", "sociale", "seashell", "sea shell"],
  societies: ["society", "secedes", "societally", "saciety", "cecity"],
  sought: ["sot", "saut", "sawt", "psat", "saat"],
  speaker: ["spieker", "spiker", "spacker", "specker", "speicher"],
  straw: ["stra", "strough", "stray", "stree", "stre"],
  stray: ["stre", "strei", "straw", "stree", "stra"],
  strongly: ["stirringly", "sternly", "staringly", "searingly", "soaringly"],
  students: ["student", "studenty", "studente", "statant", "a student"],
  study: ["studie", "steady", "studi", "stadi", "stq"],
  suit: ["suet", "sute", "suitt", "soote", "ceat"],
  surpriseing: ["surpassing", "suppressing", "sprucing", "surprises"],
  survive: ["survived", "survivor", "survives", "surviver", "cerveau"],
  swing: ["swinge", "swung", "swim", "swang", "swimm"],
  symbols: ["cymbals", "simples", "samples", "cymbal", "cimbal"],
  tapestry: ["tapestries", "tapster", "tipster", "dopesters", "dopester"],
  that: ["thot", "thaught", "thad", "theat", "thet"],
  the: ["tja", "tha", "thao", "thae", "thaa"],
  they: ["thay", "thei", "tha", "thae", "thaa"],
  thick: ["thic", "thicke", "the uk", "thec", "thack"],
  this: ["thus", "thes", "thess", "thuss", "the us"],
  three: ["thre", "thri", "thorough", "thoreau", "theroux"],
  to: ["to", "tou", "tew", "thuy", "teu"],
  too: ["to", "tou", "tew", "thuy", "teu"],
  took: ["tooke", "tac", "btec", "ptak", "taak"],
  trait: ["trate", "traite", "trade", "tourette", "terat"],
  tropical: ["topical", "typical", "tropico", "dropsical", "triacle"],
  tube: ["toob", "tab", "tabb", "t.b", "taab"],
  tugboats: ["tugboat", "tug boat", "dog bites", "tibbetts", "tibbets"],
  two: ["to", "tou", "tew", "thuy", "teu"],
  uninterrupted: [
    "uninterested",
    "unencrypted",
    "interrupted",
    "uninstructed",
    "uninterruptedly"
  ],
  upbeat: ["up beat", "up-beat", "upbeats", "appete", "a bit"],
  us: ["uhs", "usss", "usx", "usce", "'s"],
  use: ["yous", ".us", "ewes", "ews", "euse"],
  vocabulary: [
    "vocabularian",
    "vocabularies",
    "vocable",
    "vocables",
    "vocally"
  ],
  wall: ["wal", "walle", "wall-e", "wahle", "uol"],
  was: ["waas", "wahs", "wows", "waws", "uez"],
  wash: ["wosh", "watch", "waj", "wesch", "wesche"],
  water: ["watter", "watr", "wouter", "wadder", "wadr"],
  we: ["wee", "wea", "oui", "weee", "wce"],
  welcome: ["wellcome", "welkom", "welkin", "wilken", "welking"],
  were: ["wer", "whre", "worg", "wirr", "whur"],
  when: ["wen", "wehn", "wne", "wenn", "wehen"],
  who: ["hou", "hooe", "houx", "hooh", "hoogh"],
  will: ["wil", "whil", "wille", "uil", "wel"],
  wire: ["wyre", "wyer", "ywr", "waer", "waar"],
  with: ["withe", "wyth", "woth", "wath", "wythe"],
  wore: ["wor", "warr", "woar", "wahr", "warre"],
  yards: ["yard", "wards", "yarder", "yarde", "yarda"],
  year: ["yeer", "yare", "yair", "-ar", "-ior"],
  you: ["euch", "ewh", "euh", "euk", "ewg"],
  young: ["yung", "ying", "yang", "jung", "yeung"],
  your: ["yore", "ior", "yor", "-ar", "-ior"]
};

function getSuggestionDictionary() {
  return suggestionDict;
}

module.exports = getSuggestionDictionary;
