const suggestionDict = {
  cherfull: ["cherelle", "chervil", "earful", "airfoil", "cheerful"],
  "por,": ["por", "porr", "poor,", "pawer", "paur"],
  cottagge: ["cottage", "cata", "codag", "catic", "catu"],
  errends: ["errect", "behrends", "trends", "errands", "arens"],
  mad: ["madd", "magd", "madh", "made", "maad"],

  In: ["inh", "ijn", "-in", "in-", "ihn"],
  the: ["tja", "tha", "thao", "thae", "thaa"],
  living: ["loving", "leaving", "livin", "laving", "levin"],
  room: ["rhume", "roome", "reaume", "rheaume", "arame"],
  "voice-clock": ["viselike", "bicyclic", "visicalc", "o'clock", "sixoclock"],
  "sang,": ["tsang", "sangh", "cing", "sahm", "ceng"],
  "Tick-tock,": ["tiktok", "tick-tock", "tick tock", "tic-tac", "tictac"],
  seven: ["sevin", "sivan", "savan", "savin", "save on"],
  "o'clock,": ["o'clock", "oclock", "oakley", "olague", "okok"],
  time: ["tyme", "tam", "taim", "tamb", "taam"],
  to: ["to", "tou", "tew", "thuy", "teu"],
  get: ["git", "gett", "gitt", "ghit", "gibt"],
  "up,": ["upp", "aep", "epc", "aop", "ehp"],
  o: ["au", "aux", "eau", "eaux", "o'"],
  "'clock!": ["cloc", "klock", "clach", "kloc", "cloque"],
  as: ["azz", "asrt", "ass", "asse", "asce"],
  if: ["iff", "iph", "lff", "ifg", "ifh"],
  it: ["itt", "itv", "idt", "itte", "ibd"],
  were: ["wer", "whre", "worg", "wirr", "whur"],
  afrad: ["offroad", "affrayed", "afeard", "a-rod", "a rod"],
  that: ["thot", "thaught", "thad", "theat", "thet"],
  nobody: ["nobodies", "my body", "knowbot", "the body", "anybody"],
  "would.": ["wolde", "wailed", "wald", "waled", "walde"],
  The: ["tja", "tha", "thao", "thae", "thaa"],
  mornings: ["morning", "mourning", "moorings", "warnings", "mormons"],
  house: ["hous", "haus", "hause", "houss", "hausse"],
  lay: ["lae", "laye", "lait", "laigh", "laie"],
  "empty.": ["emptied", "empt", "emptier", "empie", "empi"],
  clock: ["cloc", "klock", "clach", "kloc", "cloque"],
  ticked: ["tict", "tct", "tucked", "tect", "tacked"],
  "on,": ["mwn", "-on", "nht", "lnn", "nhk"],
  repeating: ["rebooting", "rebutting", "reheating", "rabbiting", "rebating"],
  and: ["und", "unde", "undp", "end", "ende"],
  repaeting: ["reporting", "rebutting", "repainting", "reputing", "rabbiting"],
  its: ["it's", "itz", "isx", "itts", "ets"],
  sounds: ["sands", "sends", "sinds", "sondes", "scends"],
  into: ["in two", "intu", "indu", "indue", "in tow"],
  "emptiness.": ["umpteen", "umpteenth", "empyema", "emptied"],
  "Seven-nine,": [
    "seventeen",
    "seventy nine",
    "sauvignon",
    "seventy",
    "sevensome"
  ],
  breakfast: ["break fast", "breakfasts", "briefest", "prefaced", "backfist"],
  "time,": ["tyme", "tam", "taim", "tamb", "taam"],
  "seven-nine!": [
    "seven iron",
    "seventeen",
    "seventeenth",
    "seventieth",
    "sauvignon"
  ],
  kitchen: ["kitchin", "kuchen", "kishon", "kition", "cutchin"],
  stove: ["steve", "stave", "stav", "steeve", "stev"],
  gave: ["give", "giv", "gav", "gev", "ghv"],
  a: ["uh", "uhh", "eh", "eah", "aeh"],
  hissing: ["wissing", "hazing", "hitching", "hoisin", "hissings"],
  sigh: ["psi", "psy", "cye", "csae", "csy"],
  ejected: ["rejected", "dejected", "injected", "ejecta", "effected"],
  from: ["frum", "frim", "frem", "fram", "frahm"],
  warm: ["worn", "warn", "warne", "horme", "schwarm"],
  interior: ["anterior", "interiors", "interieur", "inferior", "entrar"],
  eight: ["aight", "ait", "aite", "aidt", "ajt"],
  pieces: ["peaces", "peces", "peases", "passes", "pasas"],
  of: ["uvs", "ev", "evs", "eof", "evg"],
  perfectly: [
    "perfecto",
    "perfecta",
    "perfect life",
    "perfect love",
    "perfective"
  ],
  browned: ["braund", "brond", "brawned", "brand", "brained"],
  "toast,": ["tost", "toste", "taste", "tast", "teest"],
  eggs: ["egs", "ugs", "igs", "exc", "iggs"],
  sunny: ["sonny", "sany", "signee", "seni", "seney"],
  side: ["sighed", "cide", "seid", "seide", "-cide"],
  sixteen: ["sixtine", "sexton", "sextain", "sextan", "saxton"],
  slices: ["sluices", "slicers", "splices", "seises", "sauces"],
  "bacon,": ["baken", "bacan", "bagan", "backen", "bakan"],
  two: ["to", "tou", "tew", "thuy", "teu"],
  "coffees,": ["coiffeuse", "coffee", "cafes", "coffers", "caiphas"],
  cool: ["kool", "cail", "caal", "-cle", "caille"],
  glasses: ["glass eyes", "classes", "glosses", "eyeglasses", "eye glasses"],
  "milk.": ["milke", "milc", "melk", "mlc", "melc"]
};

function getSuggestionDictionary() {
  return suggestionDict;
}

module.exports = getSuggestionDictionary;
